### ISSUE TITLE
JOSS REVIEW: voxel_thresh parameter

### ISSUE THREAD

**Issue by andrewheusser** [miykael/atlasreader#100]
As currently implemented, the `voxel_thresh` param seems a bit unintuitive to me, specifically, the fact that it switches to a different thresholding approach when a negative number is passed. I can imagine this leading to some unexpected results.  For example, say i'm a user and I run a non-parametric analysis that suggests suggests that > -10 is the appropriate statistical threshold.  How would I use the software to perform this analysis?  

If you have a good reason to keep it this way, I'd suggest outputting a warning that notifies the user of the behavior when they pass a negative `voxel_thresh`.

Also, int -> float

```
voxel_thresh: int, optional
Threshold to apply to stat_img. If a negative number is provided a percentile threshold is used instead, where the percentile is determined by the equation 100 - voxel_thresh. Default: 1.96
```

**Comment by miykael** [comment]
You're right. The documentation wasn't clear enough. The fact is, the same threshold is always applied in both directions, positive and negative, if the initial threshold value was positive. This allows the creation of figures [like this](https://github.com/miykael/atlasreader/blob/master/paper/fig_overview_figure.png).

Just thresholding images by a negative value, i.e. -10, is not possible. Would this imply thresholding everything below or above -10? I didn't have the need for this yet, but do you think that negative thresholds are required?

I've improved the description/documentation of the `voxel_thresh`/`threshold` value with https://github.com/miykael/atlasreader/pull/101. I hope that this helps and clarifies things. Is this solution for you acceptable?

And thanks for catching the "int -> float" issue. This is also corrected with https://github.com/miykael/atlasreader/pull/101. As well as some plotting issues with the `%` approach that I've discovered because of your comment (see bug fix [here](https://github.com/miykael/atlasreader/pull/101/files#diff-f1149df38e6abff71310986b3d14016eR750)).

**Comment by andrewheusser** [comment]
Thanks, I think the extended documentation clarifies things.  

So just to be clear, if the user wanted to plot only positive or only negative clusters, that's not possible with this package? Fine if it's not, but would probably be a useful feature for a future release.

**Comment by miykael** [comment]
Yes, only one-sided thresholding is currently not possible. But it makes a lot of sense, so I went ahead and implemented it with https://github.com/miykael/atlasreader/pull/107/commits/4e277c22daaee7914991f1bdeb2be903fc360236.
I've also added an example for this new parameter in the notebook, [here](https://nbviewer.jupyter.org/github/miykael/atlasreader/blob/4e277c22daaee7914991f1bdeb2be903fc360236/notebooks/atlasreader.ipynb#direction)

Thank you very much for your great feedback! It is much appreciated and helps to improve the toolbox a lot.

**Comment by miykael** [comment]
It's still not possible to threshold an image to everything above -10 or below 10, but I think for the moment this is alright.

**Comment by andrewheusser** [comment]
Awesome! This looks great. Can you add the param documentation to the readme as well?

**Comment by andrewheusser** [comment]
nevermind, i see that you did it already
