### ISSUE TITLE
JOSS REVIEW: checksum unit test failing

### ISSUE THREAD

**Issue by andrewheusser** [miykael/atlasreader#106]
The `test_table_output` unit test is failing for me locally. Not entirely sure why since it seems to pass on travis. i'll look into this later today, but if you have any ideas why let me know

**Comment by andrewheusser** [comment]
the error:
```
>       assert cluster_checksum == 'b03705caeaad17b3cbc9f9b6042bdd72'
E       AssertionError: assert '5d85805d58f8...4e34ec75d8f42' == 'b03705caeaad1...9f9b6042bdd72'
E         - 5d85805d58f8fbe22ef4e34ec75d8f42
E         + b03705caeaad17b3cbc9f9b6042bdd72

atlasreader/tests/test_atlasreader.py:179: AssertionError
```

**Comment by miykael** [comment]
Yes, this is somewhat suboptimal. I didn't want to check the peak and cluster output tables cell by cell and therefore decided to check for their checksum. My thought was, if an upstream toolbox has a new release or if I introduced a new bug that leads to changes in the output (tables and figures), then the checksum would change as well and I would be informed via this test.

But as a consequence, I manually need to verify that everything is still fine and then update the checksum myself.

Is this approach alright for you or would you have another suggestion? I could also assert a few columns against a specified list. Columns like t-value, cluster size or coordinate.

**Comment by andrewheusser** [comment]
You could use `pandas` to compare a saved csv to one generated in the test. Something like this:

```
    df = pd.DataFrame([1, 2, 3])
    df2 = pd.DataFrame([1, 2, 3])
    df.equals(df2)
```

**Comment by miykael** [comment]
Thank you for the input. I chose `numpy` instead of pandas (so that I don't need to worry about headers).
The commit https://github.com/miykael/atlasreader/pull/107/commits/f59357e3f46b627264e16aa32e9312dc5e30313a is implementing this solution.

I chose not to test for atlas label outputs to keep the [hardcoded tables](https://github.com/miykael/atlasreader/pull/107/commits/f59357e3f46b627264e16aa32e9312dc5e30313a#diff-557a7b66ddf62ddbfa41c57aac19529cR44) small. Do you think I should include the atlas label output as well?

**Comment by andrewheusser** [comment]
I think this is a sufficient test, looks good!
