### ISSUE TITLE
update packaging

### ISSUE THREAD

**Issue by Remi-Gau** [miykael/atlasreader#128]
- move to pyproject.toml
- support more recent pythons
- ...

**Comment by miykael** [comment]
In your PR https://github.com/miykael/atlasreader/pull/131, I've added some minimal version numbers to have at least some restrictions. I hopefully chose them reasonably, but they are also arbitrary and can definitely be changed to something else if you think that's better.

With regards to moving to pyproject.toml, definitely fine by me.

**Comment by Remi-Gau** [comment]
OK will try update packaging now

**Comment by Remi-Gau** [comment]
closing this as done

may be worth cutting a new release to pypi: this way I would feel able to close this issue on nilearn https://github.com/nilearn/nilearn/issues/3940

**Comment by miykael** [comment]
Hello @Remi-Gau. I create a new release on github but to be honest don't know how to do one on pypi. My usual approach does not seem to work due to a missing info.py file, did this got lost or can you perhaps help me with getting a new release out to PyPi?

Also, I apologise, I wasn't aware that you did all of this work to integrate some of this packages functionality into nilearn. Thanks again for all this work! It's much appreciated!

**Comment by Remi-Gau** [comment]
> I create a new release on github but to be honest don't know how to do one on pypi. My usual approach does not seem to work due to a missing info.py file, did this got lost or can you perhaps help me with getting a new release out to PyPi?

I could either add some info in a contributing.md regarding the release process with instructions to follow or create a github action that should push to pypi when you make a github release (the latter will require you to set up some pypi token).

Any preference?


> Also, I apologise, I wasn't aware that you did all of this work to integrate some of this packages functionality into nilearn.

Well I figured it was better to fix an old wheel rather than reinvent one.

**Comment by miykael** [comment]
I appologize for the very late reply, but I think I was able to resolve the issue with the package update. It might have been connected with a missing `info.py` file, or something else. Surprisingly, ChatGPT was super helpful in debugging everything - took 10min.

Newest version of atlasreader==0.3.1 should now work without problem.

**Comment by Remi-Gau** [comment]
Sorry I did not see this.
OK things are publishedon pypi but it is weird from a packaging point of view.
You probably don't want to have both setup.py / info.py and pyproject.toml because this duplicates package info.
What was the issue you were having?

**Comment by miykael** [comment]
Happy to remove things if I can. I think the problem was that I thought I need setup.py, which relies on info.py (see [here](https://github.com/miykael/atlasreader/blob/master/setup.py#L10), and that this file was missing.

I didn't realize that I could have also just removed setup.py and info.py and build the package with hatch. I will remove them, so that we only keep pyproject.toml.
