### ISSUE TITLE
CLI in demo notebook not up to date

### ISSUE THREAD

**Issue by danjgale** [miykael/atlasreader#36]
The demo notebook hasn't been updated to work with the new CLI. I guess the older version I had running for #32 was still using old files I had from a while ago, so it _appeared_ to work despite the changes. Oops. I'm working on fixing it right now, with _new_ files. 

Relatedly, if we make any changes, I think its a good idea that we should run the demo notebook as a last test (in addition to testing the code). This way we can integrate changes into the notebook right away. Thoughts?

**Comment by miykael** [comment]
Very good idea! You can `pytest` to run and test a notebook. I've implemented it already in many different repos (see [here](https://github.com/miykael/fmriflows/blob/master/scripts/test_notebooks.py#L126)).

The command is something like: `pytest --nbval-lax --nbval-cell-timeout 7200 -v -s  Demo.ipynb`

And once you've run it (for example on circleci), you get something like [this](https://circleci.com/gh/miykael/fmriflows/90) (click on `run test 1` and scroll down a bit).

**Comment by danjgale** [comment]
Excellent, didn't know about that feature! Thanks

**Comment by miykael** [comment]
But I'm not sure how to use it in travis. Perhaps as simple as that as well :-)

**Comment by rmarkello** [comment]
I didn't know there was a`pytest` [extension](https://github.com/computationalmodelling/nbval) for that!!! That's **amazing**!!

We can set up another environment in the `.travis.yml` matrix to explicitly test the jupyter notebooks. It should be relatively straightforward since we already have two&mdash;one for testing coverage and the other for linting&mdash;so we could do something like `NOTEBOOKS=1` in the new environment and just make sure we install `jupyter` and `nbval` along with the normal `pytest` related packages.
