### ISSUE TITLE
Is default cluster_extent of 20 good or bad?

### ISSUE THREAD

**Issue by miykael** [miykael/atlasreader#43]
I'm not sure if it's a good idea to have the default value of `cluster_extent` at 20, [here](https://github.com/miykael/atlasreader/blob/master/atlasreader/atlasreader.py#L600).

I personally prefer to have it at around 5. We could put it at 0, but I agree, creating a output plot for every 1-voxel cluster might be overkill.

What does everybody think?

**Comment by rmarkello** [comment]
The whole concept of cluster extent based thresholding has been pretty [critically examined](http://www.pnas.org/content/113/28/7900) in the past few years, so I'm hesitant to put anything too low that people might misuse. We could instead make `cluster_extent` a **required** argument so that users have to provide it themselves? That way we wouldn't be responsible for a default number that might be misinterpreted...
