### ISSUE TITLE
Do you know app.codacy.com?

### ISSUE THREAD

**Issue by miykael** [miykael/atlasreader#62]
I was just made aware of https://app.codacy.com and it seems to be very cool.
If I understand correctly then you can use this site to check the quality of your code. We currently have a `B` for `atlasreader`, where we would like to have an `A`.

This is because we have 24 security issues, 1 error issue, 1 code style issue, and 1 unused code issue: see https://app.codacy.com/project/miykael/atlasreader/dashboard

Do you know about this service and would you like to join it?

**Comment by rmarkello** [comment]
From what I've heard it sounds like Codacy doesn't necessarily add a whole lot of value if you're already using traditional integrated testing (e.g., with Travis or CircleCI), code coverage, and linting&mdash;which we are! :tada:

All the "security issues" seem to be due to our use of `assert` statements in testing&mdash;which I think are standard when using `pytest`! Moreover, adding more `assert` statements (and more tests) is apparently sufficient to fail a PR (e.g., #65) 🙁

For those reasons I suppose I'm probably a "no" vote on codacy, but I'm definitely open to discussion, too! 🙂

**Comment by miykael** [comment]
Good points. I was just curious in what way the mentioned "security issues" with `assert` and others are really an issue or not.

And I agree, the fact that the PR will fail because of this is annoying. I will disable this functionality again. Nonetheless, the discussion for it can stay open for a bit.

**Comment by danjgale** [comment]
I'm thinking 'no' on this one too. I think the setup we have right now is pretty sufficient, in addition to some pretty savvy code reviewers we have on the team!

**Comment by miykael** [comment]
I'm ok with a 'no' :+1: Therefore, I will close this issue now.
