### ISSUE TITLE
Using this to label something other than a stat image

### ISSUE THREAD

**Issue by saigerutherford** [miykael/atlasreader#74]
Hey guys. So awesome that this project is going strong! 

So I am trying to use this tool to give anatomical labels to all of the ROIs in the Power 264-node functional atlas. The power atlas is just a csv file of xyz MNI coordinates, but I turned it into an image with 5mm spheres around each ROI (and then smoothed it). When I run this image through create_output with these settings: 

`create_output(img,
              cluster_extent=0,
              atlas=['aal','Harvard-Oxford'],outdir='.')
`
I get this error: 

`/Users/saigerutherford/.local/lib/python3.6/site-packages/nilearn/plotting/displays.py:684: UserWarning: empty mask
  get_mask_bounds(new_img_like(img, not_mask, affine))`

Is this just too many clusters to identify and they're too small? When I plot the image using `plotting.plot_glass_brain(img)`
it looks fine. Thanks for any feedback you can give :)

**Comment by miykael** [comment]
Hey @saigerutherford, great that you're using `atlasreader`.

The number or size of clusters shouldn't be an issue. But I'm not familiar with this error. I'm curious if it is an issue of overlap (does your atlas overlap with the MNI152 template) or number of volumes (does your atlas have 3 or 4 dimensions?

The best way to debug this is to have access to your atlas. Is there a way you can share it?

**Comment by saigerutherford** [comment]
yes I can share the atlas. It is 3D and it should be in MNI space. What's the easiest way for me to share? Its 278 MB.

**Comment by miykael** [comment]
Whatever is easiest for you. Do you have it on Dropbox and could share a link?

**Comment by miykael** [comment]
First, that looks really cool.
![new](https://user-images.githubusercontent.com/950321/46496076-5a531f00-c817-11e8-8b3d-ae22774c512e.png)

Second, `atlasreader` should be able to also handle non-stat images. But your NIfTI revealed some interesting points/bugs.
1. It's a bug that the software crashes when an image is empty (adressed in https://github.com/miykael/atlasreader/issues/75). And the image is empty because we have a default value for `threshold`, set at 2. That's a problem because the maximum value in your image is much smaller (around 0.48). So, it will help if you change this parameter to something smaller.
2. Nonetheless, it will most likely still crash because of a memory error. Your image has a really high resolution (iso 0.5mm^3 resolution with 394, 466, 378 voxels). Too manx voxels, togehter with too many clusters, might cause an issue in [this section](https://github.com/miykael/atlasreader/blob/master/atlasreader/atlasreader.py#L462). It's where we extract all relevant clusters. But we somehow also create a copy of the data matrix, which in your case makes everything just explode :-) @rmarkello do you see a quick way how to solve this?

**Comment by miykael** [comment]
There are some ways how you can bypass those issues:
1. Do you need such a high voxel resolution? If not, then I would start by increasing the voxel size to 1.0.
2. I recommend to reduce the file size, to reduce the memory load. You currently use `float32`. By switching to `int16` you reduce file size already by have. Of course, to switch from float to int, you would need to change the values in the file. `int16` goes up to 32'000 and your max value is 0.48. So I recommend multiplying all values by a factor of 10'000. FSL makes this very simple:
`fslmaths Power.nii -mul 10000 Power_int.nii -odt short`
If you want to use Python, then you can do it as follows:
   ```python
   import nibabel as nb
   img = nb.load('PowerAtlas_5mm-smoothed.nii')
   data = (img.get_data() * 10000).astype('int16')
   img.set_data_dtype('int16')
   new_img = nb.Nifti1Image(data, affine=img.affine, header=img.header)
   nb.save(new_img, 'PowerAtlas_5mm-smoothed_int.nii')
   ```
3. You can reduce file size even further by cropping away the slices that only contain zero. This might cause an issue for your further analysis, if all of your images need to have the same number of voxels. But if not, then using the following code will reduce file size again by half:
   ```python
   from nilearn.image import crop_img
   crop_img(new_img).to_filename('PowerAtlas_5mm-smoothed_crop.nii')
   ```
4. (optional) As a last step, you can compress the file and get the overall file size to 5.2MB. But this step doesn't reduce the memory consumption in `atlasreader` just the foot print on your hard drive.

Let me know if that helps somehow.

**Comment by rmarkello** [comment]
Hey @saigerutherford ! Thanks so much for making this issue :slightly_smiling_face: 

@miykael is entirely correct about the statistical threshold (`voxel_thresh` if you're calling `create_output()` directly) being imposed: the reason the UserWarning is being raised is because it's detecting a totally empty image! The default threshold is 1.96 (we assume a z-stat image is provided), so you should probably lower it a bit. We defnitely should raise a more helpful error for that, which is why @miykael created #75.

Unfortunately, even if you set `voxel_thresh` to 0, you're going to get a nonsense output because your image has only a single cluster. That is, your smoothed, 5mm radius spheres are actually ALL touching one another!

In order to circumvent this I would recommend _not_ smoothing the image after you create the 5mm radius spheres and try running this again with the following call:

```python
create_output(img, cluster_extent=0, voxel_thresh=0, atlas=['aal', 'harvard_oxford'], outdir='.')
```

If you're insistent on the smoothing, you have a few other options:

1. Set `min_distance=1`, which will make the program look for sub-peaks in the image. Note that in this case the cluster table will be meaningless (you'll only get one cluster), so you'll have to examine the peak table which will only give you the anatomical IDs of the original Power coordinates. I don't think this is what you want!
2. Play around with non-zero `voxel_thresh` values (e.g., `voxel_thresh=0.2`). This should disconnect most of the clusters from one another so you will get interpretable cluster _and_ peak tables. On the downside, the clusters will no longer be ~5mm radius spheres, so this might not be totally ideal.

I would also recommend following @miykael's suggestions in his most recent comment (reducing the voxel size, file size, etc.). You'll see a significant speed-up in how quickly `atlasreader` runs (this is a big image, so it's going to take a lot of memory and a LONG while to run...).

Let us know if any of these work for you or if you keep having issues!

**Comment by miykael** [comment]
I've tried to optimize the code in [this section](https://github.com/miykael/atlasreader/blob/master/atlasreader/atlasreader.py#L462) to allow the analysis of bigger files but wasn't able to find a good solution. The problem is, if a 3D nifti file is 200MB but has 100 clusters, it will create a temporary file of the size 200MB * 100.

The only other solution I see is the usage of `scipy.ndimage`'s `label` function. Something like this:
```python
# Detect individual clusters in data
labels, nlabels = label(data)

# Remove clusters that are too small
for idx in range(1, nlabels + 1):
    if np.sum(labels == idx) < cluster_extent:
        labels[labels == idx] = 0

# Count number of clsuters
number_of_clusters += len(np.setdiff1d(np.unique(labels), [0]))
```
Something like this wouldn't explode the memory consumption but would imply that we need to rewrite a huge part of the code, so that `process_img` doesn't return a 4D image, but only a 3D image with the labels for each cluster. Consequently, all following functions would need to create 3D cluster images on the fly.

Because of this, and because this is a rather special case (huge number of clusters and high resolution image), I'm inclined to leave the code as it is.
